version: '3.8'

services:
  weather-mysql:
    image: mysql:8
    container_name: weather-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Puji2002@
      MYSQL_DATABASE: weather_db

    ports:
      - "3307:3306" # Change the external port to 3307
    networks:
      - weather-network

  weather-app:
    build: .
    container_name: weather-app
    restart: always
    depends_on:
      - weather-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://weather-mysql:3306/weather_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Puji2002@
    ports:
      - "6161:6161"
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
