apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: poojitak/weather-app:latest  # Replace with your actual Docker Hub image
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://weather-mysql:3306/weather_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Puji2002@"
          ports:
            - containerPort: 6161
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 6161
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:  # This must be outside livenessProbe
            httpGet:
              path: /actuator/health
              port: 6161
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 6161
      targetPort: 6161
      nodePort: 30008  # Exposes the app on Minikube
